apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-translator
  labels:
    app: bot-translator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-translator
  template:
    metadata:
      labels:
        app: bot-translator
    spec:
      containers:
        - name: bot-translator
          image: 172.20.10.120:5000/smart-bot-translator:v1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-translator-secret
                  key: BOT_TOKEN
            - name: LLM_URL
              value: "http://172.20.10.47:12434"
            - name: LLM_MODEL
              value: "docker.io/ai/qwen3:4B-UD-Q8_K_XL"
            - name: USE_LLM
              value: "true"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
